### ISSUE TITLE
عربي اون لاين 

### ISSUE THREAD

**Issue by RANSyoyo** [pi-apps/PiOS#113]
عملة باي هي عمله ذات مصداقية في كل العملات سوف يكون لها صيت في كل بقاع العالم نحنو العرب يجب دعمها تعالو لنحصل عليها اخوتي انا اعدن عملة الباي منذ سنتين سوف تكتسح جميع العملات ومن ضمنها البتكوين انا اقترح علئ منفذين العمله لجعلها تدعم المشلولين والمعوقين لكي تكون مصدر دخل قوي لنا من الجانب الإنساني يتم توزيع كل شخص من المعوقين في العالم كله عمله 100k لدعمنا اخوتي

**Comment by b2h4a2** [comment]
Good luck 
GCV 1π=314159$ and Good 
From Egypt

**Comment by medjamac** [comment]
Ok

**Comment by medjamac** [comment]
kaalmeeyaan

**Comment by medjamac** [comment]
Hi
