### ISSUE TITLE
pi-flutter-sdk

### ISSUE THREAD

**Issue by CCCinici** [pi-apps/PiOS#44]
Hi,
Stellar has much more sdk options and pi network might add some other language's sdk. This is a more project, more community options, speed up for project. i think. Maybe access for restfullAPI. 

Btw. I need more documentation(video/blog) for sdk's. Thanks.

**Comment by pi-core-team** [comment]
Hello, are you looking to contribute a flutter SDK to the PiOS library? If so this can be done by making a Pull Request on the list.md file of this repository. There are a number of developers who've contributed other languages such as python or C# so we are trying to grow the list of available languages

**Comment by CCCinici** [comment]
Thank you for your respond. I will.
