### ISSUE TITLE
@huachina2021

### ISSUE THREAD

**Issue by huachina2023** [pi-apps/PiOS#76]
![IMG20230623120729](https://github.com/pi-apps/PiOS/assets/137469183/6a967921-8d87-4c4e-9f51-bfd027bf9f5e)

**Comment by huachina2023** [comment]
祝pi早日开放主网

**Comment by huachina2023** [comment]
I  am student

**Comment by huachina2023** [comment]
https://github.com/pi-apps/PiOS/assets/137469183/4d4d5493-6cfb-4112-b889-99d5350c1cc4

Dig and Dig

**Comment by huachina2023** [comment]
https://github.com/pi-apps/PiOS/assets/137469183/ba1e92bd-07a0-46de-9046-bc4fab965b2f

What flowers, what fruit.

**Comment by Sahnesiguzel33** [comment]
Yani?

**Comment by Opapai051148** [comment]
Ok friend.Let me learn more#

**Comment by Opapai051148** [comment]
I'm a pioneer.need to learn more and more

**Comment by Opapai051148** [comment]
I'm a pioneer.need to learn more and more.
