### ISSUE TITLE
PI network 

### ISSUE THREAD

**Issue by Husnad** [pi-apps/PiOS#80]
nice projects

**Comment by Alvaromeo999** [comment]
App_whd for Pi

**Comment by hungnguyenvn47** [comment]
Dự án tốt !

**Comment by Sahnesiguzel33** [comment]
Hello

iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________
Gönderen: hungnguyenvn47 ***@***.***>
Gönderildi: Wednesday, July 12, 2023 4:27:18 AM
Kime: pi-apps/PiOS ***@***.***>
Bilgi: Subscribed ***@***.***>
Konu: Re: [pi-apps/PiOS] PI network (Issue #80)


Dự án tốt !

**Comment by Opapai051148** [comment]
Thanks friend.Good morning and happy together#

**Comment by Pi4440** [comment]
#80
