### ISSUE TITLE
素描

### ISSUE THREAD

**Issue by Jhwcl007** [pi-apps/PiOS#89]
> 眼里的牙
![mmexport1682650645575](https://github.com/pi-apps/PiOS/assets/136962638/a0e32d5f-c25b-459d-a084-a5c4a1fb1470)

**Comment by Opapai051148** [comment]
Eyes is usefull

**Comment by Jhgzh007** [comment]
有一定的创意

**Comment by Sahnesiguzel33** [comment]
> 眼里的牙
> ![mmexport1682650645575](https://user-images.githubusercontent.com/136962638/256385361-a0e32d5f-c25b-459d-a084-a5c4a1fb1470.jpg)
